package com.npucraft.battleroyale.combat;
public enum DamageOrigin { PLAYER_MELEE, PROJECTILE, EXPLOSION, FIRE, LAVA, FALL, ZONE, DROWNING, VOID, MOB, MAGIC, OTHER, DISCONNECT_TIMEOUT, DISCONNECT_BODY_FAILURE }
