package com.lastsector.recovery;
import com.lastsector.offline.BodySnapshot;
import com.lastsector.loadout.StoredItem;
import com.lastsector.zone.*;
import java.util.*;
/** Version 1 wire DTO. All times are durations/elapsed values, never persisted nanoTime origins. */
public record SessionRecoverySnapshot(int snapshotVersion,UUID sessionId,String roomId,String mapId,String worldName,String relativePath,String gameState,long revision,long elapsedNanos,String rulesHash,List<Team> teams,List<Participant> participants,ZoneState zone,long protectionRemainingNanos,List<Hit> hits,List<Box> boxes,Set<Long> sanitizedBlocks,Set<Long> sanitizedEntities,String lootState,Outcome outcome,long showcaseRemainingNanos,com.lastsector.progression.SessionProgress.Snapshot progression,com.lastsector.admin.MapMetadata mapMetadata) {
    public SessionRecoverySnapshot(int snapshotVersion,UUID sessionId,String roomId,String mapId,String worldName,String relativePath,String gameState,long revision,long elapsedNanos,String rulesHash,List<Team> teams,List<Participant> participants,ZoneState zone,long protectionRemainingNanos,List<Hit> hits,List<Box> boxes,Set<Long> sanitizedBlocks,Set<Long> sanitizedEntities,String lootState,Outcome outcome,long showcaseRemainingNanos,com.lastsector.progression.SessionProgress.Snapshot progression) {this(snapshotVersion,sessionId,roomId,mapId,worldName,relativePath,gameState,revision,elapsedNanos,rulesHash,teams,participants,zone,protectionRemainingNanos,hits,boxes,sanitizedBlocks,sanitizedEntities,lootState,outcome,showcaseRemainingNanos,progression,null);}
    public SessionRecoverySnapshot(int snapshotVersion,UUID sessionId,String roomId,String mapId,String worldName,String relativePath,String gameState,long revision,long elapsedNanos,String rulesHash,List<Team> teams,List<Participant> participants,ZoneState zone,long protectionRemainingNanos,List<Hit> hits,List<Box> boxes,Set<Long> sanitizedBlocks,Set<Long> sanitizedEntities,String lootState,Outcome outcome,long showcaseRemainingNanos) { this(snapshotVersion,sessionId,roomId,mapId,worldName,relativePath,gameState,revision,elapsedNanos,rulesHash,teams,participants,zone,protectionRemainingNanos,hits,boxes,sanitizedBlocks,sanitizedEntities,lootState,outcome,showcaseRemainingNanos,null); }
    public record Team(UUID id,int index,Set<UUID> members){public Team{members=Set.copyOf(members);}}
    public record Participant(UUID id,String name,String state,UUID team,int kills,int assists,LobbySnapshot lobby,BodySnapshot current,long reconnectRemainingNanos) {}
    public record ZoneState(Zone initial,Zone current,Zone from,Zone next,int stage,ZonePhase phase,long remainingNanos) {public ZoneState{Objects.requireNonNull(initial);Objects.requireNonNull(current);Objects.requireNonNull(from);Objects.requireNonNull(phase);if(stage<0 || remainingNanos<0 || phase!=ZonePhase.FINAL && next==null || phase==ZonePhase.FINAL && (next!=null || remainingNanos!=0))throw new IllegalArgumentException("Invalid zone phase");}}
    public record Hit(UUID victim,UUID attacker,double amount,String origin,long ageNanos,boolean direct) {public Hit{Objects.requireNonNull(victim);Objects.requireNonNull(attacker);com.lastsector.combat.DamageOrigin.valueOf(origin);if(victim.equals(attacker) || !Double.isFinite(amount) || amount<=0 || ageNanos<0)throw new IllegalArgumentException("Invalid hit");}}
    public record Box(UUID id,UUID deceased,String name,double x,double y,double z,long elapsedNanos,String cause,UUID killer,Set<UUID> assists,boolean direct,Map<Integer,StoredItem> inventory){public Box{assists=Set.copyOf(assists);inventory=Map.copyOf(inventory);Objects.requireNonNull(id);Objects.requireNonNull(deceased);com.lastsector.combat.DamageOrigin.valueOf(cause);if(!Double.isFinite(x)||!Double.isFinite(y)||!Double.isFinite(z)||elapsedNanos<0||inventory.keySet().stream().anyMatch(slot->slot<0||slot>=54))throw new IllegalArgumentException("Invalid DeathBox");}}
    public record Outcome(Set<UUID> players,Set<UUID> teams,boolean tie,String reason,long tick){public Outcome{players=Set.copyOf(players);teams=Set.copyOf(teams);}}
    public SessionRecoverySnapshot {
        Objects.requireNonNull(sessionId);Objects.requireNonNull(roomId);Objects.requireNonNull(mapId);Objects.requireNonNull(worldName);Objects.requireNonNull(relativePath);Objects.requireNonNull(rulesHash);com.lastsector.session.GameState.valueOf(gameState);teams=List.copyOf(teams);participants=List.copyOf(participants);hits=List.copyOf(hits);boxes=List.copyOf(boxes);sanitizedBlocks=Set.copyOf(sanitizedBlocks);sanitizedEntities=Set.copyOf(sanitizedEntities);
        if(snapshotVersion!=1 || revision<1 || elapsedNanos<0 || protectionRemainingNanos<0 || showcaseRemainingNanos<0)throw new IllegalArgumentException("Invalid session metadata");
        var ids=new HashSet<UUID>();for(var p:participants){Objects.requireNonNull(p.id());Objects.requireNonNull(p.name());com.lastsector.player.PlayerState.valueOf(p.state());if(!ids.add(p.id()) || p.kills()<0 || p.assists()<0 || p.reconnectRemainingNanos()<0)throw new IllegalArgumentException("Invalid participant");if(gameState.equals("RUNNING") && Set.of("ALIVE","DISCONNECTED").contains(p.state()) && (p.current()==null || p.current().health()<=0))throw new IllegalArgumentException("Missing active participant state");}
        var members=new HashSet<UUID>();var teamIds=new HashSet<UUID>();for(var t:teams){if(!teamIds.add(t.id()) || t.index()<1 || t.members().isEmpty())throw new IllegalArgumentException("Invalid Team");for(UUID id:t.members())if(!members.add(id))throw new IllegalArgumentException("Duplicate Team member");}
        if(!members.equals(ids))throw new IllegalArgumentException("Team roster mismatch");
        for(var p:participants)if(teams.stream().noneMatch(t->t.id().equals(p.team()) && t.members().contains(p.id())))throw new IllegalArgumentException("Participant Team mismatch");
        if(gameState.equals("RUNNING") || gameState.equals("ENDING")){if(zone==null || !lootState.equals("COMPLETE"))throw new IllegalArgumentException("Incomplete gameplay snapshot");if(gameState.equals("ENDING") && outcome==null)throw new IllegalArgumentException("Missing outcome");}
        if(outcome!=null && (!ids.containsAll(outcome.players()) || !teamIds.containsAll(outcome.teams())))throw new IllegalArgumentException("Invalid outcome identities");
        if(progression!=null) {
            if(!progression.frozen().keySet().equals(ids))throw new IllegalArgumentException("Progression roster mismatch");
            var placementTeams=new HashSet<>(progression.placements().unresolved());placementTeams.addAll(progression.placements().assigned().keySet());
            if(!placementTeams.equals(teamIds))throw new IllegalArgumentException("Progression Team mismatch");
            if(progression.result()!=null && !progression.result().sessionId().equals(sessionId))throw new IllegalArgumentException("Result session mismatch");
            new com.lastsector.progression.SessionProgress(progression);
        }
        if(boxes.stream().map(Box::id).distinct().count()!=boxes.size())throw new IllegalArgumentException("Duplicate deathbox");
    }
}
