package com.lastsector.recovery;
import com.lastsector.loadout.StoredItem;import com.lastsector.offline.*;import com.lastsector.zone.*;import java.util.*;import org.junit.jupiter.api.Test;import static org.junit.jupiter.api.Assertions.*;
class SnapshotCodecTest {
 final SnapshotCodec codec=new SnapshotCodec();final UUID session=UUID.randomUUID(),player=UUID.randomUUID(),team=UUID.randomUUID();final StoredItem item=new StoredItem("paper-native",1,"AQID");
 LobbySnapshot lobby(){return new LobbySnapshot(Map.of(0,item,40,item),Map.of(2,item),item,3,12,.25f,400,"CREATIVE",12,14,3,0,List.of(new BodySnapshot.Effect("minecraft:speed",1200,2,false,true,true)),0,0,0,true,false);}
 SessionRecoverySnapshot full(){var body=new BodySnapshot(new BodyPosition(UUID.randomUUID(),1,64,2,90,0),18,24,2,16,2,0,200,0,List.of(new BodySnapshot.Effect("minecraft:health_boost",500,0,false,true,true)),Map.of(0,item,40,item),item,5,7,.5f,101);var initial=new Zone(0,0,500);var next=new Zone(30,40,250);
 return new SessionRecoverySnapshot(1,session,"solo","city","plugins/LastSector/runtime/safe","safe","RUNNING",42,123000,"rules",List.of(new SessionRecoverySnapshot.Team(team,1,Set.of(player))),List.of(new SessionRecoverySnapshot.Participant(player,"Alice","DISCONNECTED",team,2,3,lobby(),body,90_000_000_000L)),new SessionRecoverySnapshot.ZoneState(initial,ZoneGeometry.interpolate(initial,next,.5),initial,next,0,ZonePhase.SHRINKING,5_000_000_000L),20_000_000_000L,List.of(),List.of(new SessionRecoverySnapshot.Box(UUID.randomUUID(),player,"Alice",1,64,2,100,"FALL",null,Set.of(),false,Map.of(8,item,53,item))),Set.of(0L,123L),Set.of(0L),"COMPLETE",null,0);}
 @Test void fullDtoRoundTripsWithoutBukkitObjects(){var value=full();var encoded=codec.encode(value);assertEquals(value,codec.decode(encoded.version(),encoded.json(),encoded.checksum(),SessionRecoverySnapshot.class));assertFalse(encoded.json().contains("nanoTime"));assertEquals(lobby(),codec.decode(1,codec.encode(lobby()).json(),codec.encode(lobby()).checksum(),LobbySnapshot.class));}
 @Test void corruptionIsRejectedBeforeParsing(){var encoded=codec.encode(full());assertThrows(IllegalArgumentException.class,()->codec.decode(1,encoded.json()+" ",encoded.checksum(),SessionRecoverySnapshot.class));assertThrows(IllegalArgumentException.class,()->codec.decode(999,encoded.json(),encoded.checksum(),SessionRecoverySnapshot.class));assertThrows(IllegalArgumentException.class,()->codec.decode(1,"{",SnapshotCodec.hash("{"),SessionRecoverySnapshot.class));}
 @Test void mapAndSetOrderDoNotChangeBytes(){var a=new LinkedHashMap<String,Object>();a.put("z",new LinkedHashSet<>(List.of(3,1,2)));a.put("a",1);var b=new LinkedHashMap<String,Object>();b.put("a",1);b.put("z",new LinkedHashSet<>(List.of(2,3,1)));assertEquals(codec.encode(a),codec.encode(b));}
 @Test void invalidNativePayloadAndSlotsRejected(){assertThrows(IllegalArgumentException.class,()->new StoredItem("paper-native",1,"!!!"));assertThrows(IllegalArgumentException.class,()->new SessionRecoverySnapshot.Box(UUID.randomUUID(),player,"A",0,0,0,0,"FALL",null,Set.of(),false,Map.of(54,item)));}
 @Test void rejectsMissingActiveStateAndInvalidRoster(){var value=full();var tree=new com.google.gson.Gson().toJsonTree(value).getAsJsonObject();tree.getAsJsonArray("participants").get(0).getAsJsonObject().remove("current");String text=tree.toString();final String missing=text;assertThrows(RuntimeException.class,()->codec.decode(1,missing,SnapshotCodec.hash(missing),SessionRecoverySnapshot.class));tree.getAsJsonArray("teams").get(0).getAsJsonObject().add("members",new com.google.gson.JsonArray());text=tree.toString();final String bad=text;assertThrows(RuntimeException.class,()->codec.decode(1,bad,SnapshotCodec.hash(bad),SessionRecoverySnapshot.class));}
}
