package com.npucraft.lastsector.player;
import java.util.*;import java.util.concurrent.*;import org.junit.jupiter.api.Test;import static org.junit.jupiter.api.Assertions.*;
class DurabilityBarrierTest {
 UUID player=UUID.randomUUID(),session=UUID.randomUUID();List<String> events=new ArrayList<>();CompletableFuture<Void> commit=new CompletableFuture<>();
 PlayerIsolation<String,String> isolation(){var value=new PlayerIsolation<String,String>(new PlayerIsolation.Gateway<>(){public String capture(UUID id){events.add("capture");return "original";}public void apply(UUID id,String item){events.add("apply");}public boolean restore(UUID id,String snapshot){assertEquals("original",snapshot);events.add("restore");return true;}},(id,error)->fail(error));value.durability(new PlayerIsolation.Durability<>(){public CompletionStage<Void> store(UUID id,Map<UUID,String> rows){events.add("store");return commit;}public void pending(UUID id){events.add("pending");}});return value;}
 @Test void commitPrecedesDestructiveMutation(){var value=isolation();var future=value.applyAsync(session,List.of(player),"kit");assertEquals(List.of("capture","store"),events);assertTrue(value.blocked(player));assertFalse(value.ready(session));commit.complete(null);assertTrue(future.toCompletableFuture().isDone());assertEquals(List.of("capture","store","apply"),events);assertFalse(value.blocked(player));value.end(session);assertEquals(List.of("capture","store","apply","pending","restore"),events);}
 @Test void failedCommitNeverMutatesAndUnfreezes(){var value=isolation();var future=value.applyAsync(session,List.of(player),"kit");commit.completeExceptionally(new IllegalStateException());assertTrue(future.toCompletableFuture().isCompletedExceptionally());assertEquals(List.of("capture","store"),events);assertFalse(value.blocked(player));assertFalse(value.ready(session));}
 @Test void cancelledPreparationRestoresCommittedOriginalWithoutApplying(){var value=isolation();var future=value.applyAsync(session,List.of(player),"kit",()->false);commit.complete(null);assertTrue(future.toCompletableFuture().isCompletedExceptionally());assertEquals(List.of("capture","store","pending","restore"),events);assertFalse(value.blocked(player));}
 @Test void duplicateApplyCannotRaceBarrier(){var value=isolation();value.applyAsync(session,List.of(player),"kit");assertThrows(IllegalStateException.class,()->value.applyAsync(UUID.randomUUID(),List.of(player),"kit"));commit.complete(null);}
 @Test void synchronousStoreFailureUnfreezes(){var value=isolation();value.durability(new PlayerIsolation.Durability<>(){public CompletionStage<Void> store(UUID s,Map<UUID,String> rows){throw new IllegalStateException();}public void pending(UUID id){}});assertTrue(value.applyAsync(session,List.of(player),"kit").toCompletableFuture().isCompletedExceptionally());assertFalse(value.blocked(player));}
 @Test void repeatedRestoreConsumesPendingOnlyOnce(){var value=isolation();value.recover(session,player,"original",true);value.retry(player);value.retry(player);assertEquals(List.of("restore"),events);}
}
