package com.npucraft.battleroyale.storage;
import com.npucraft.battleroyale.recovery.SnapshotCodec;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import static org.junit.jupiter.api.Assertions.*;
class RecoveryRepositoryTest {
 @TempDir Path root; JdbcStorageProvider provider; JdbcRecoveryRepository repo; UUID owner=UUID.randomUUID(),session=UUID.randomUUID();
 @BeforeEach void setup()throws Exception{provider=new JdbcStorageProvider(StorageSettings.defaults("sqlite",root));repo=new JdbcRecoveryRepository(provider);assertEquals(SchemaMigrations.VERSION,repo.migrate());}
 RecoveryRepository.Row row(long revision){return new RecoveryRepository.Row(session,"solo","city","safe-world","RUNNING",revision,1,"{}",SnapshotCodec.hash("{}"),123,"ACTIVE");}
 RecoveryRepository.Restore original(UUID player,UUID generation){return new RecoveryRepository.Restore(player,session,generation,1,"{}",SnapshotCodec.hash("{}"),"ORIGINAL",123);}
 @Test void migrationIsRepeatableAndPreservesRows()throws Exception{repo.save(row(1),owner,100);assertEquals(SchemaMigrations.VERSION,repo.migrate());assertEquals(1,repo.sessions().size());}
 @org.junit.jupiter.params.ParameterizedTest @org.junit.jupiter.params.provider.ValueSource(ints={-1,999}) void refusesUnsupportedSchemaWithoutResettingData(int version)throws Exception{repo.save(row(1),owner,100);try(var c=provider.connect();var s=c.createStatement()){s.executeUpdate("UPDATE battleroyale_schema SET version="+version);}assertThrows(Exception.class,repo::migrate);assertEquals(1,repo.sessions().size());}
 @Test void delayedAndDuplicateRevisionsCannotOverwrite()throws Exception{assertTrue(repo.save(row(10),owner,100));assertFalse(repo.save(row(9),owner,100));assertFalse(repo.save(row(10),owner,100));assertEquals(10,repo.sessions().getFirst().revision());}
 @Test void concurrentWritersKeepHighestRevision()throws Exception{repo.save(row(1),owner,100);try(var pool=Executors.newFixedThreadPool(2)){var a=pool.submit(()->repo.save(row(20),owner,100));var b=pool.submit(()->repo.save(row(10),owner,100));a.get();b.get();}assertEquals(20,repo.sessions().getFirst().revision());}
 @Test void claimHasOneOwnerUntilExpiryAndOldOwnerCannotWrite()throws Exception{UUID next=UUID.randomUUID();repo.save(row(1),owner,100);assertFalse(repo.claim(session,next,99,200));assertTrue(repo.claim(session,next,100,200));assertFalse(repo.save(row(2),owner,300));assertTrue(repo.save(row(2),next,300));}
 @Test void wrongOwnerCannotRetireOrPromoteOriginals()throws Exception{UUID player=UUID.randomUUID();repo.save(row(1),owner,100);repo.originals(List.of(original(player,UUID.randomUUID())));assertThrows(Exception.class,()->repo.retire(session,UUID.randomUUID(),"COMPLETED"));assertEquals("ORIGINAL",repo.restores().getFirst().status());assertEquals(1,repo.sessions().size());}
 @Test void retirementPromotesOriginalsAndCannotBeResurrected()throws Exception{repo.save(row(1),owner,100);repo.originals(List.of(original(UUID.randomUUID(),UUID.randomUUID())));repo.retire(session,owner,"ABANDONED");assertTrue(repo.sessions().isEmpty());assertEquals("PENDING",repo.restores().getFirst().status());assertFalse(repo.save(row(999),owner,200));}
 @Test void originalsBatchIsAtomicOnCollision()throws Exception{UUID a=UUID.randomUUID(),b=UUID.randomUUID();repo.originals(List.of(original(a,UUID.randomUUID())));assertThrows(Exception.class,()->repo.originals(List.of(original(b,UUID.randomUUID()),original(a,UUID.randomUUID()))));assertEquals(List.of(a),repo.restores().stream().map(RecoveryRepository.Restore::player).toList());}
 @Test void deletionRequiresAppliedAndMatchingGeneration()throws Exception{UUID player=UUID.randomUUID(),old=UUID.randomUUID(),fresh=UUID.randomUUID();repo.originals(List.of(original(player,old)));repo.deleteRestore(player,old);assertEquals(1,repo.restores().size());assertFalse(repo.applied(player,fresh));assertTrue(repo.applied(player,old));repo.deleteRestore(player,old);repo.originals(List.of(original(player,fresh)));repo.deleteRestore(player,old);assertEquals(fresh,repo.restores().getFirst().generation());}
 @Test void dataSurvivesNewRepositoryConnection()throws Exception{repo.save(row(4),owner,100);assertEquals(4,new JdbcRecoveryRepository(new JdbcStorageProvider(StorageSettings.defaults("sqlite",root))).sessions().getFirst().revision());}
 @Test void sqlValuesAreParameters()throws Exception{var r=row(1);repo.save(new RecoveryRepository.Row(session,"x'; DROP TABLE recovery_sessions; --",r.map(),r.world(),r.state(),1,1,r.payload(),r.checksum(),0,r.status()),owner,100);assertEquals(1,repo.sessions().size());}
 @Test void databaseExecutorIsNamedAndNeverRunsOverflowOnCaller()throws Exception{var entered=new CountDownLatch(1);var release=new CountDownLatch(1);try(var executor=new DatabaseExecutor(1,e->{})){var first=executor.submit(()->{entered.countDown();release.await();return Thread.currentThread().getName();});assertTrue(entered.await(5,TimeUnit.SECONDS));var second=executor.submit(()->1);var rejected=executor.submit(()->2);assertThrows(ExecutionException.class,()->rejected.get());release.countDown();assertEquals("BattleRoyale-database",first.get());assertEquals(1,second.get());}finally{release.countDown();}}
 @Test void mysqlDriverIsPackagedAndSettingsRejectUrlInjection()throws Exception{assertNotNull(Class.forName("com.mysql.cj.jdbc.Driver"));assertThrows(IllegalArgumentException.class,()->new StorageSettings("mysql",root,"host/?password=x",3306,"db","user","secret",1000));assertFalse(new StorageSettings("mysql",root,"localhost",3306,"db","user","secret",1000).toString().contains("secret"));}
}
